fieldFight:
  namespace: field-fight-dev
  releaseName: field-fight-dev
  services:
    - auth-service
    - leaderboard-api
    - match-history-service
    - game-server

grafana:
  hostname: grafana-dev.shri.software

kube-prometheus-stack: {}
loki: {}
promtail: {}
