imageTag: 05e85f63368ee895cff432c228b0f9b0215805d7

registry:
  accountId: "272772901676"
  region: us-east-1
  repositoryPrefix: field-fight

database:
  host: field-fight-dev-postgres.cjzrv40mvlrb.us-east-1.rds.amazonaws.com
  port: 5432
  name: fieldfight
  user: fieldfight
  password: ""
  ssl: true

urls:
  frontend: https://field-fight-qa.shri.software
  service: https://field-fight-qa.shri.software

config:
  nodeEnv: production
  port: "3000"
  corsOrigin: "*"

auth:
  jwtSecret: ""
  googleClientId: ""
  googleClientSecret: ""
  githubClientId: ""
  githubClientSecret: ""

secrets:
  create: false
  existingSecret: field-fight-qa-secrets

ingress:
  enabled: true
  className: alb
  host: field-fight-qa.shri.software
  certificateArn: ""
  annotations: {}
