imageTag: 6e4c1848c6319d8751db4ead9f305fd55c8d4e6c

registry:
  accountId: "272772901676"
  region: us-east-1
  repositoryPrefix: field-fight

database:
  host: field-fight-dev-postgres.cjzrv40mvlrb.us-east-1.rds.amazonaws.com
  port: 5432
  name: fieldfight
  user: fieldfight
  password: ""
  ssl: true

urls:
  frontend: https://field-fight-qa.shri.software
  service: https://field-fight-qa.shri.software

config:
  nodeEnv: production
  port: "3000"
  corsOrigin: "*"

auth:
  jwtSecret: ""
  googleClientId: ""
  googleClientSecret: ""
  githubClientId: ""
  githubClientSecret: ""

secrets:
  create: false
  existingSecret: field-fight-qa-secrets

ingress:
  enabled: true
  className: alb
  host: field-fight-qa.shri.software
  certificateArn: arn:aws:acm:us-east-1:272772901676:certificate/381413c6-6e74-4bd1-9534-34f4f19cc5c5
  groupName: field-fight
  annotations: {}
