{{- range .Values.fieldFight.services }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: field-fight-{{ . }}
  labels:
    release: {{ $.Release.Name | quote }}
    app.kubernetes.io/part-of: field-fight
spec:
  namespaceSelector:
    matchNames:
      - {{ $.Values.fieldFight.namespace | quote }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Values.fieldFight.releaseName | quote }}
      app.kubernetes.io/component: {{ . | quote }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
{{- end }}
