imageTag: 3bfcd5999caab21997c579e61b8f72cd5cbd5d78

registry:
  accountId: "272772901676"
  region: us-east-1
  repositoryPrefix: field-fight

database:
  host: field-fight-dev-postgres.cjzrv40mvlrb.us-east-1.rds.amazonaws.com
  port: 5432
  name: fieldfight
  user: fieldfight
  password: ""
  ssl: true

urls:
  frontend: https://field-fight.shri.software
  service: https://field-fight.shri.software

config:
  nodeEnv: production
  port: "3000"
  corsOrigin: "*"

auth:
  jwtSecret: ""
  googleClientId: ""
  googleClientSecret: ""
  githubClientId: ""
  githubClientSecret: ""

secrets:
  create: false
  existingSecret: field-fight-prod-secrets

ingress:
  enabled: true
  className: alb
  host: field-fight.shri.software
  certificateArn: arn:aws:acm:us-east-1:272772901676:certificate/c3dcd5c3-f2a1-4756-aa7a-cc380049745c
  groupName: field-fight
  annotations: {}
