imageTag: 467f4bcc10fff206f5491f422f80d8323292679b

registry:
  accountId: "272772901676"
  region: us-east-1
  repositoryPrefix: field-fight

database:
  host: field-fight-dev-postgres.cjzrv40mvlrb.us-east-1.rds.amazonaws.com
  port: 5432
  name: fieldfight
  user: fieldfight
  password: ""
  ssl: true

urls:
  frontend: https://field-fight-uat.shri.software
  service: https://field-fight-uat.shri.software

config:
  nodeEnv: production
  port: "3000"
  corsOrigin: "https://field-fight-uat.shri.software"

auth:
  jwtSecret: ""
  googleClientId: ""
  googleClientSecret: ""
  githubClientId: ""
  githubClientSecret: ""

secrets:
  create: false
  existingSecret: field-fight-uat-secrets

ingress:
  enabled: true
  className: alb
  host: field-fight-uat.shri.software
  certificateArn: arn:aws:acm:us-east-1:272772901676:certificate/abfd19fa-61a0-4801-b949-f8734e5a3466
  groupName: field-fight
  annotations: {}
