imageTag: 74275f78b717c385de47ec3fdc6150e502463e56

registry:
  accountId: "272772901676"
  region: us-east-1
  repositoryPrefix: field-fight

database:
  host: field-fight-dev-postgres.cjzrv40mvlrb.us-east-1.rds.amazonaws.com
  port: 5432
  name: fieldfight
  user: fieldfight
  password: ""
  ssl: true

urls:
  frontend: https://field-fight-dev.shri.software
  service: https://field-fight-dev.shri.software

config:
  nodeEnv: production
  port: "3000"
  corsOrigin: "https://field-fight-dev.shri.software"

auth:
  jwtSecret: ""
  googleClientId: ""
  googleClientSecret: ""
  githubClientId: ""
  githubClientSecret: ""

secrets:
  create: false
  existingSecret: field-fight-dev-secrets

ingress:
  enabled: true
  className: alb
  host: field-fight-dev.shri.software
  certificateArn: arn:aws:acm:us-east-1:272772901676:certificate/add088d8-2103-4f42-b65b-7a49cd1d3c63
  groupName: field-fight
  annotations: {}
